apiVersion: v1
kind: Namespace
metadata:
  name: rosistat
  labels:
    kubernetes.io/metadata.name: rosistat
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted